export const FIELD_UPDATE = 'FIELD_UPDATE';
export const FIELDS_UPDATE = 'FIELDS_UPDATE';
export const FIELD_SET_ERROR = 'FIELD_SET_ERROR';
export const REGISTER_FIELD = 'REGISTER_FIELD';
export const DEREGISTER_FIELD = 'DEREGISTER_FIELD';
export const REGISTER_FIELD_ARRAY = 'REGISTER_FIELD_ARRAY';
export const DEREGISTER_FIELD_ARRAY = 'DEREGISTER_FIELD_ARRAY';
export const ARRAY_PUSH = 'ARRAY_PUSH';
export const ARRAY_REMOVE = 'ARRAY_REMOVE';
export const INCREMENT_ERROR_COUNT = 'INCREMENT_ERROR_COUNT';
export const TOUCH_FIELD = 'TOUCH_FIELD';
export const START_SUBMIT = 'START_SUBMIT';
export const STOP_SUBMIT = 'STOP_SUBMIT';

